Disallow lex compatibility options like %a.
See description and rationale added to smflex.html.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -332,6 +332,16 @@ out/c-prefix-validated.ok: out/c-prefix.ok
 	fi
 	touch $@
 
+# Run $(SMFLEX) on an input that should provoke a syntax error.
+all: out/invalid-pct-a.bad
+out/invalid-pct-a.bad: invalid-pct-a.lex $(SMFLEX)
+	@mkdir -p out
+	if $(SMFLEX) $(SMFLEX_OPTS) $($(TEST_CONFIG)_OPS) -oout/invalid-pct-a.lex.c $<; then \
+	  echo "That should have failed!"; \
+	  exit 2; \
+	fi
+	touch $@
+
 # Unit test program.
 out/test-eval-skel-expr.exe: test-eval-skel-expr.c ../eval-skel-expr.h ../eval-skel-expr.c
 	$(CC) -o$@ $(CFLAGS) -I.. test-eval-skel-expr.c ../eval-skel-expr.c
